### ISSUE TITLE
Not working with current version of Marionette (v3.3.0)

### ISSUE THREAD

**Issue by arturmiglio** [maratfakhreev/marionette-animated-region#4]
The removeView function seems to have been renamed.

On line 68, `this._removeView(view, options);` should now be `this.removeView(view, options);`

**Comment by maratfakhreev** [comment]
@arturmiglio I'll check it, thank you. Did you use it with Marionette 3.x.x?

**Comment by arturmiglio** [comment]
@maratfakhreev yes. I even forked it to bypass the error, but in the end went with a different solution (because of other reasons), so I can't be sure if my changes would solve everything, as I did not run any serious testing. 

It would be nice to have your module working for future uses, I like the approach.

**Comment by maratfakhreev** [comment]
@arturmiglio I've fixed this bug in 2.1.0, also fixed test env to avoid same problems in future. Feel free to update your dependenies and thank you for the issue find.
